### ISSUE TITLE
Poor compression ratio for large strings

### ISSUE THREAD

**Issue by jamievicary** [pierrec/node-lz4#37] opened 2015-12-09 16:21 UTC
I am using node-lz4 in the browser, to compress and decompress blocks. When my string to be compressed goes above roughly 65535 bytes, the compression ratio jumps up from about 10% to about 250% --- i.e., it is actually making my data much longer.

Is there a maximum block size limit for this implementation? I can't see it mentioned anywhere.

So, maybe this is a bug.

**Comment by pierrec** [comment] 2015-12-10 08:54
Hello,

The compression ratio is not directly related to the size of the input data. Unless your data is not compressible, you should be able to have a smaller compressed data set.

Now, do you have a test case which reproduces your issue?
Is your data compressible?

Also, try to compress your data with the command line encoder both nodejs and js based, see under the examples directory:
node examples/file_compress.js
node examples/file_compressJS.js

**Comment by jamievicary** [comment] 2015-12-10 10:04
Here's the issue exhibited in a jsfiddle:

https://jsfiddle.net/h8rf3rf1/

If I compress the first 65535 characters of my string, the compression ratio is 38%. But if I compress the first 65536 characters, the ratio is 138%. Maybe I'm just using the library wrong, in which case, it would be good to know in what way.

**Comment by pierrec** [comment] 2015-12-10 10:39
Hmm. There seems to be an issue with the CompressBlock() function: it compresses your data into around 29Kb instead of 4Kb for other implementations I have.
Investigating.

**Comment by jamievicary** [comment] 2015-12-10 10:40
Thanks. Glad I am not going crazy :).

**Comment by pierrec** [comment] 2015-12-10 20:28
Ok, fixed in v0.5.1.

Thanks for the report and test data!

**Closed by pierrec** 2015-12-10 20:28 UTC

**Comment by jamievicary** [comment] 2015-12-10 21:58
Fantastic, great work, the fixed library is live in my project already.
