### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by selshas** [pierrec/node-lz4#102] opened 2020-07-07 08:20 UTC
If i do install lz4 through npm or yarn, it fails with follow lines.

node.h(673):  warning C4819 ..\lib\binding\lz4_binding.cc
lz4_binding.cc(8): fatal error C1083 '../../deps/lz4/lib/lz4.h': No such file or directory

node.h(673):  warning C4819 ..\lib\binding\xxhash_binding.cc
lz4_binding.cc(8): fatal error C1083 '../../deps/lz4/lib/xxhash.h': No such file or dir

gyp ERR! build error

**Comment by ankon** [comment] 2020-07-07 08:47
Duplicate of https://github.com/pierrec/node-lz4/issues/99

**Closed** 2021-01-04 14:29 UTC
